<a href="https://colab.research.google.com/github/guddlaraji/files/blob/main/Raji_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#05-08-2025

**Introduction to pandas**

In [ ]:
#what is pandas?
#pandas is a open source library where it deals with labelled data
#why we use the pandas?
#fast, high-performence, and productive and easy to load the data
#flexible reshaping of the data, pivoting the data, Data visualisation and group by functionality
#time series analysis

In [ ]:
#what is the function of pandas?
#Analysing the data, cleaning, exploring, and manipulating the data
#what is Data Cleaning?
#delete irrelevent rows, empty or null values,correction of data types,fill the null values

**installation of Pandas**

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#import the module
import pandas as pd

In [ ]:
#How many data structures do we have in pandas?
#3 types
#1.Series:- series are nothing but 1D Labelled array

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]

In [ ]:
#convert the above array into series
sr = pd.Series(a)
print(sr)
print(sr.shape)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
(6,)

In [ ]:
#give the customized index for above series
sr = pd.Series(a,index=['a','b','c','d','e','f'])
print(sr)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [ ]:
#create a series from dictionary
d = {
    "name":'medha',
    "course":"DS",
    "Duration":"4months"
}
sr = pd.Series(d)
print(sr)

name          medha
course           DS
Duration    4months
dtype: object

In [ ]:
#create a series from tuple of fruits and give the labels a,b,c,d,e
#create a series from list of fruits and give the labels a,b,c,d,e

In [ ]:
"""#create a series from set of number?
s = {1,2,3,4}
a = pd.Series(s)
print(a)
#we cannot create a series from the SET because it is unordered
#pd.Series(collection_name,index=[])"""

'#create a series from set of number?\ns = {1,2,3,4}\na = pd.Series(s)\nprint(a)\n#we cannot create a series from the SET because it is unordered\n#pd.Series(collection_name,index=[])'

In [ ]:
l = ['apple','lemon','banana','mango','orange']
a = pd.Series(l)
print(a)

0     apple
1     lemon
2    banana
3     mango
4    orange
dtype: object

In [ ]:
print(a[0])

apple

**2D-DataFrame**

In [ ]:
#Dataframe is a 2D size ,Heterogenous data with labelled axis(rows and columns)
#columns also known as --> features,varaibles, fields
#rows also known as --> records, values and index

In [ ]:
#what is the application of DataFrame?
#works on datasets
#analysis
#dropping
#processing
#cleaning
#join the multiple data
#create the excel, json..etc
#compute the mathematical and statistical operations
#use group by function

In [ ]:
#create a df from the list of numbers
l = [1,2,3,4,5,6]
df = pd.DataFrame(l)
print(df)
df.shape

   0
0  1
1  2
2  3
3  4
4  5
5  6

(6, 1)

In [ ]:
#create a dataframe from the set
s1 = {'apple','banana','orange','pineapple'}
df = pd.DataFrame(s1,index=['a','b','c','d'])
print(df)
#Note:- we can create a df from the SET

           0
a     banana
b      apple
c     orange
d  pineapple

In [ ]:
#create a dataframe from the dictionary
d = {
    "name":'medha',
    "course":"DS",
    "Duration":"4months"
}

df = pd.DataFrame(d,index=['a','b'])
print(df)

    name course Duration
a  medha     DS  4months
b  medha     DS  4months

**exporting and importing the Data**

In [ ]:
#read the csv file
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
#convert the above file into excel format
df.to_excel('sample.xlsx')

In [ ]:
#read the json file
df1 = pd.read_excel("/content/sample.xlsx")
df1.head()
#export the excel file into json format
df1.to_json('sample.json')

In [ ]:
#read the json file
df2 = pd.read_json("/content/sample.json")
df2.head()

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,0,-114.31,34.19,15,5612,1283,1015,472,1.4936,66900
1,1,-114.47,34.40,19,7650,1901,1129,463,1.8200,80100
2,2,-114.56,33.69,17,720,174,333,117,1.6509,85700
3,3,-114.57,33.64,14,1501,337,515,226,3.1917,73400
4,4,-114.57,33.57,20,1454,326,624,262,1.9250,65500

**DataFrame functions**

In [ ]:
#step1:- read the data sample csv file
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
#step2:- check the size and index of above df
df.size   #--> no of rows * no of columns
df.index

RangeIndex(start=0, stop=17000, step=1)

In [ ]:
#read the column of df
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
#check the number of rows and columns
df.shape

(17000, 9)

In [ ]:
#get the overall info about the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
#print the data types
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
#print the summery of your df according descriptive stats
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
#print last five rows of df
df.tail(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16990,-124.22,41.73,28.0,3003.0,699.0,1530.0,653.0,1.7038,78300.0
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,2.4805,73200.0
16992,-124.23,40.81,52.0,1112.0,209.0,544.0,172.0,3.3462,50800.0
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

This df is having 17000 rows

There is no null values

for all the columns the dtype is float

**Accessing the DataFrames**

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
#access the column of 'total_rooms' from above dataframe
df['total_rooms']
df.total_rooms

0        5612.0
1        7650.0
2         720.0
3        1501.0
4        1454.0
          ...
16995    2217.0
16996    2349.0
16997    2677.0
16998    2672.0
16999    1820.0
Name: total_rooms, Length: 17000, dtype: float64

In [ ]:
#read the first 5 rows of total_rooms
df['total_rooms'].head()
df['total_rooms'].tail()

16995    2217.0
16996    2349.0
16997    2677.0
16998    2672.0
16999    1820.0
Name: total_rooms, dtype: float64

In [ ]:
#print the first row value of 'total_rooms'
df['total_rooms'][100:120]

100    2183.0
101     935.0
102     709.0
103    1629.0
104    1121.0
105    1009.0
106    1228.0
107    1564.0
108     348.0
109     749.0
110    1586.0
111     452.0
112     472.0
113      96.0
114    1660.0
115    3868.0
116     208.0
117    1210.0
118     459.0
119    1321.0
Name: total_rooms, dtype: float64

In [ ]:
#Acess the multiple columns  'total_bedrooms', 'population', 'households', 'median_income'
df[['total_bedrooms', 'population', 'households', 'median_income']]

       total_bedrooms  population  households  median_income
0              1283.0      1015.0       472.0         1.4936
1              1901.0      1129.0       463.0         1.8200
2               174.0       333.0       117.0         1.6509
3               337.0       515.0       226.0         3.1917
4               326.0       624.0       262.0         1.9250
...               ...         ...         ...            ...
16995           394.0       907.0       369.0         2.3571
16996           528.0      1194.0       465.0         2.5179
16997           531.0      1244.0       456.0         3.0313
16998           552.0      1298.0       478.0         1.9797
16999           300.0       806.0       270.0         3.0147

[17000 rows x 4 columns]

loc():- is used to locate the rows

In [ ]:
#syntax:- df.loc[start:end:step]
#print the entire 1st row?
df.loc[0]

longitude              -114.3100
latitude                 34.1900
housing_median_age       15.0000
total_rooms            5612.0000
total_bedrooms         1283.0000
population             1015.0000
households              472.0000
median_income             1.4936
median_house_value    66900.0000
Name: 0, dtype: float64

In [ ]:
#print the row index from 100 to 108
df.loc[100:108]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
100,-115.59,32.79,8.0,2183.0,307.0,1000.0,287.0,6.3814,159900.0
101,-115.59,32.69,30.0,935.0,177.0,649.0,148.0,2.5769,94400.0
102,-115.60,33.20,37.0,709.0,187.0,390.0,142.0,2.4511,72500.0
103,-115.60,32.87,3.0,1629.0,317.0,1005.0,312.0,4.1293,83200.0
104,-115.62,33.04,20.0,1121.0,244.0,766.0,230.0,2.2969,62000.0
105,-115.62,33.04,17.0,1009.0,231.0,745.0,217.0,2.0463,61200.0
106,-115.64,32.80,23.0,1228.0,235.0,569.0,235.0,3.1667,125000.0
107,-115.69,32.79,18.0,1564.0,340.0,1161.0,343.0,2.1792,55200.0
108,-115.72,32.75,16.0,348.0,99.0,123.0,54.0,2.0938,87500.0

In [ ]:
#read the even and odd index rows
df.loc[::2]
df.loc[1::2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0
...,...,...,...,...,...,...,...,...,...
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,2.4805,73200.0
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
#display the even index position values of particular columns
#'population'
df['population'][::2]
#print by using the loc
df.loc[::2,'population']
df['population'].loc[::2]

0        1015.0
2         333.0
4         624.0
6        1841.0
8        3134.0
          ...
16990    1530.0
16992     544.0
16994     434.0
16996    1194.0
16998    1298.0
Name: population, Length: 8500, dtype: float64

In [ ]:
df[['total_bedrooms', 'population', 'households', 'median_income']].loc[::2]

       total_bedrooms  population  households  median_income
0              1283.0      1015.0       472.0         1.4936
2               174.0       333.0       117.0         1.6509
4               326.0       624.0       262.0         1.9250
6               680.0      1841.0       633.0         2.6768
8              1175.0      3134.0      1056.0         2.1782
...               ...         ...         ...            ...
16990           699.0      1530.0       653.0         1.7038
16992           209.0       544.0       172.0         3.3462
16994           419.0       434.0       187.0         1.9417
16996           528.0      1194.0       465.0         2.5179
16998           552.0      1298.0       478.0         1.9797

[8500 rows x 4 columns]

In [ ]:
df.loc[::2,['total_bedrooms', 'population', 'households', 'median_income']]

       total_bedrooms  population  households  median_income
0              1283.0      1015.0       472.0         1.4936
2               174.0       333.0       117.0         1.6509
4               326.0       624.0       262.0         1.9250
6               680.0      1841.0       633.0         2.6768
8              1175.0      3134.0      1056.0         2.1782
...               ...         ...         ...            ...
16990           699.0      1530.0       653.0         1.7038
16992           209.0       544.0       172.0         3.3462
16994           419.0       434.0       187.0         1.9417
16996           528.0      1194.0       465.0         2.5179
16998           552.0      1298.0       478.0         1.9797

[8500 rows x 4 columns]

#6-08-2025

**Applying conditions in DataFrame**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df =pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
#loc():- is used to locate the rows
#to apply the condition in dataframe we use the loc()
#print the even values of above dataframe column "total_rooms"
df['total_rooms'] %2==0
df.loc[df['total_rooms']%2==0]['total_rooms']

0        5612.0
1        7650.0
2         720.0
4        1454.0
7         812.0
          ...
16992    1112.0
16993    2694.0
16994    1430.0
16998    2672.0
16999    1820.0
Name: total_rooms, Length: 8355, dtype: float64

In [ ]:
#locate the rows of indexes 6500,2500,700
df.loc[[6500,2500,7000]]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
6500,-118.27,33.98,45.0,1696.0,424.0,1502.0,429.0,1.3042,99200.0
2500,-117.63,34.37,20.0,7052.0,1306.0,2197.0,810.0,3.7252,167100.0
7000,-118.31,33.94,40.0,1550.0,278.0,798.0,270.0,3.7750,153800.0

In [ ]:
#print the even number data from below array
a = np.array([10,12,13,15,16,17,19,18,13,16])
print(a%2==0)
a_even = a[a%2==0]
print(a_even)
b = np.where(a%2==0,a,None)
print(b)

[ True  True False False  True False False  True False  True]
[10 12 16 18 16]
[10 12 None None 16 None None 18 None 16]

i loc pass axis number of rows and columns

In [ ]:
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c)
#syntax : [row_index,col_index]
print(c[1,1])
print(c[1,3])

[[1 2 3 4]
 [5 6 7 8]]
6
8

In [ ]:
#syntax of iloc :-  df.iloc[row_index,col_index]
#print the first 3index rows with first 3index columns from above df
print(df.iloc[0:4,0:4])

   longitude  latitude  housing_median_age  total_rooms
0    -114.31     34.19                15.0       5612.0
1    -114.47     34.40                19.0       7650.0
2    -114.56     33.69                17.0        720.0
3    -114.57     33.64                14.0       1501.0

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
#print 1rows  value of housing median age-->o/p:- 19
df.iloc[1,2]
df.iloc[4,3]

np.float64(1454.0)

In [ ]:
#print the first 100 index rows along with first 5 index columns
df.iloc[0:101:2,0:6]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0
2,-114.56,33.69,17.0,720.0,174.0,333.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0
10,-114.60,33.62,16.0,3741.0,801.0,2434.0
12,-114.61,34.84,48.0,1291.0,248.0,580.0
14,-114.63,32.76,15.0,1448.0,378.0,949.0
16,-114.65,33.60,28.0,1678.0,322.0,666.0
18,-114.66,32.74,17.0,1388.0,386.0,775.0
20,-114.68,33.49,20.0,1491.0,360.0,1135.0
22,-114.94,34.55,20.0,350.0,95.0,119.0
24,-115.22,33.54,18.0,1706.0,397.0,3424.0
26,-115.37,32.82,30.0,1602.0,322.0,1130.0
28,-115.37,32.81,32.0,741.0,191.0,623.0
30,-115.38,32.82,38.0,1892.0,394.0,1175.0
32,-115.39,32.76,16.0,1136.0,196.0,481.0
34,-115.40,32.70,19.0,583.0,113.0,531.0
36,-115.46,33.19,33.0,1234.0,373.0,777.0
38,-115.48,32.68,15.0,3414.0,666.0,2097.0
40,-115.49,32.69,17.0,1960.0,389.0,1691.0
42,-115.49,32.67,25.0,2322.0,573.0,2185.0
44,-115.50,32.68,18.0,3631.0,913.0,3565.0
46,-115.51,33.24,32.0,1995.0,523.0,1069.0
48,-115.51,32.99,20.0,1402.0,287.0,1104.0
50,-115.52,34.22,30.0,540.0,136.0,122.0
52,-115.52,33.12,38.0,1327.0,262.0,784.0
54,-115.52,32.97,24.0,1617.0,366.0,1416.0
56,-115.52,32.77,18.0,1715.0,337.0,1166.0
58,-115.52,32.67,6.0,2804.0,581.0,2807.0
60,-115.53,32.99,25.0,2578.0,634.0,2082.0
62,-115.53,32.97,34.0,2231.0,545.0,1568.0
64,-115.54,32.99,23.0,1459.0,373.0,1148.0
66,-115.54,32.98,27.0,1513.0,395.0,1121.0
68,-115.54,32.79,23.0,1712.0,403.0,1370.0
70,-115.55,32.98,24.0,2565.0,530.0,1447.0
72,-115.55,32.80,23.0,666.0,142.0,580.0
74,-115.55,32.79,22.0,565.0,162.0,692.0
76,-115.56,32.96,21.0,2164.0,480.0,1164.0
78,-115.56,32.80,25.0,1311.0,375.0,1193.0
80,-115.56,32.79,20.0,2372.0,835.0,2283.0
82,-115.56,32.78,46.0,2511.0,490.0,1583.0
84,-115.56,32.78,29.0,1568.0,283.0,848.0
86,-115.57,32.85,33.0,1365.0,269.0,825.0
88,-115.57,32.84,29.0,1207.0,301.0,804.0
90,-115.57,32.80,16.0,2276.0,594.0,1184.0
92,-115.57,32.78,20.0,1534.0,235.0,871.0
94,-115.58,33.88,21.0,1161.0,282.0,724.0
96,-115.58,32.81,10.0,1088.0,203.0,533.0
98,-115.58,32.78,5.0,2494.0,414.0,1416.0
100,-115.59,32.79,8.0,2183.0,307.0,1000.0

In [ ]:
#what is the difference between loc and iloc?
#loc supports filtering where iloc won't support filtering of data
#we can apply condition in loc where we cannot apply condition in iloc
df.iloc[df['total_rooms']%2==0]['total_rooms']

In [ ]:
#locate the first 10 rows of following columns 'population',housing_median_age,households,median_income
df[['population','housing_median_age','households','median_income']].loc[:10]

    population  housing_median_age  households  median_income
0       1015.0                15.0       472.0         1.4936
1       1129.0                19.0       463.0         1.8200
2        333.0                17.0       117.0         1.6509
3        515.0                14.0       226.0         3.1917
4        624.0                20.0       262.0         1.9250
5        671.0                29.0       239.0         3.3438
6       1841.0                25.0       633.0         2.6768
7        375.0                41.0       158.0         1.7083
8       3134.0                34.0      1056.0         2.1782
9        787.0                46.0       271.0         2.1908
10      2434.0                16.0       824.0         2.6797

In [ ]:
#find the duplicate data from above dataframe?
df.duplicated().sum()

np.int64(0)

In [ ]:
#drop the duplicates
df.drop_duplicates(inplace=True)

In [ ]:
#access the single column from df---> df['col']
#access the multiple columns from df---> df[['col1','col2']]
#locate the particular row of data--> df.loc[start:end:step]
#print specific value from specific column--> df.iloc[row_index,col_index]
#find the unique() values ---> df['col_name'].unique()
#**Get the frequency of data in particular column--> df['col'].value_counts()

In [ ]:
df['total_rooms'].value_counts()

total_rooms
1582.0    16
1527.0    15
1471.0    14
1703.0    14
1717.0    14
          ..
3904.0     1
4922.0     1
3091.0     1
5496.0     1
5315.0     1
Name: count, Length: 5533, dtype: int64

**Handling the missing data**

In [ ]:
s = pd.Series(['sam',np.nan,'Tim'])
print(s)

0    sam
1    NaN
2    Tim
dtype: object

In [ ]:
#check the null values
s.isnull().sum()

np.int64(1)

In [ ]:
s.notnull()

0     True
1    False
2     True
dtype: bool

In [ ]:
#how can we drop the null values
s.dropna()

0    sam
2    Tim
dtype: object

In [ ]:
from numpy import nan as NA

In [ ]:
df = pd.DataFrame([[1,2,3],[4,NA,5],[NA,NA,NA]])
df

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0
2  NaN  NaN  NaN

In [ ]:
#check the null values from dataframe
df.isnull().sum()

0    1
1    2
2    1
dtype: int64

In [ ]:
#in above dataframe drop the null values
df.dropna()

     0    1    2
0  1.0  2.0  3.0

In [ ]:
#delete only the rows having all the null values
df.dropna(how= 'all')

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0

In [ ]:
#replace the 1st rows 2nd column value as a NA
df.iloc[0,1] = NA

In [ ]:
#delete the columns which is having all the null values
df.dropna(how='all',axis=1)

     0    2
0  1.0  3.0
1  4.0  5.0
2  NaN  NaN

In [ ]:
#thresh :- minimum number of Non-NA values required to keep a row or column
#df.dropna(thresh=N) it keeps only the rows and columns that has atleast "N" non-Na vlaues
df = pd.DataFrame([[1,2,3],[4,NA,5],[NA,NA,NA]])
df.dropna(thresh = 2)   #minimum count of non-null values in rows must be 3

     0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  5.0

In [ ]:
#remove the null values column wise with the thresh of 2 non null values in column
df.dropna(thresh=2,axis=1)
#df.dropna(how="any/all",axis= 0 or 1,thresh=N, inplace=True/False)

     0    2
0  1.0  3.0
1  4.0  5.0
2  NaN  NaN

**ill the null values**

In [ ]:
#How to fill the null values--> fill it with zeros
df = pd.DataFrame([[1,2,3],[4,NA,5],[NA,NA,NA]])
df.fillna(0)

     0    1    2
0  1.0  2.0  3.0
1  4.0  0.0  5.0
2  0.0  0.0  0.0

In [ ]:
#fill the column wise null values for each give a different value for ex col index 0 fill it with 15,
#col index 2 fill it with 25 and col_index fill it with 35
df.fillna({0:15,1:25,2:35})

      0     1     2
0   1.0   2.0   3.0
1   4.0  25.0   5.0
2  15.0  25.0  35.0

In [ ]:
df.fillna(method='ffill',limit=1)

/tmp/ipython-input-393035141.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',limit=1)

     0    1    2
0  1.0  2.0  3.0
1  4.0  2.0  5.0
2  4.0  NaN  5.0

In [ ]:
#fill the null values with the menan
df.fillna(df.mean())
#df.fillna(value,method,limit,inplace)

     0    1    2
0  1.0  2.0  3.0
1  4.0  2.0  5.0
2  2.5  2.0  4.0